services:
  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile

  app:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile

  worker:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile

  scheduler:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
